"""audit log survives account deletion

Revision ID: 5f4f638655ee
Revises: 2ede86f3673b
Create Date: 2026-09-27 13:55:45.931950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4f638655ee'
down_revision: Union[str, Sequence[str], None] = '2ede86f3673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_log', 'actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admin_audit_log', 'target_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('admin_audit_log_actor_user_id_fkey'), 'admin_audit_log', type_='foreignkey')
    op.drop_constraint(op.f('admin_audit_log_target_user_id_fkey'), 'admin_audit_log', type_='foreignkey')
    op.create_foreign_key('admin_audit_log_target_user_id_fkey', 'admin_audit_log', 'users', ['target_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('admin_audit_log_actor_user_id_fkey', 'admin_audit_log', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_audit_log_target_user_id_fkey', 'admin_audit_log', type_='foreignkey')
    op.drop_constraint('admin_audit_log_actor_user_id_fkey', 'admin_audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('admin_audit_log_target_user_id_fkey'), 'admin_audit_log', 'users', ['target_user_id'], ['id'])
    op.create_foreign_key(op.f('admin_audit_log_actor_user_id_fkey'), 'admin_audit_log', 'users', ['actor_user_id'], ['id'])
    op.alter_column('admin_audit_log', 'target_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin_audit_log', 'actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
