"""curriculum modules

Revision ID: 783ae404ad87
Revises: dc3ebffc3f6c
Create Date: 2026-09-28 12:08:23.110338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783ae404ad87'
down_revision: Union[str, Sequence[str], None] = 'dc3ebffc3f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.add_column('lessons', sa.Column('module_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('description', sa.String(length=2000), server_default='', nullable=False))
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'course_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_column('lessons', 'description')
    op.drop_column('lessons', 'module_id')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
    # ### end Alembic commands ###
