"""creator marketplace fields

Revision ID: dc3ebffc3f6c
Revises: 5f4f638655ee
Create Date: 2026-09-28 11:59:30.717164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc3ebffc3f6c'
down_revision: Union[str, Sequence[str], None] = '5f4f638655ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_profiles_user_id'), 'creator_profiles', ['user_id'], unique=True)
    op.add_column('courses', sa.Column('creator_user_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('category', sa.String(length=120), server_default='', nullable=False))
    op.add_column('courses', sa.Column('outcomes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('courses', sa.Column('target_audience', sa.String(length=500), server_default='', nullable=False))
    op.add_column('courses', sa.Column('requirements', sa.String(length=1000), server_default='', nullable=False))
    op.add_column('courses', sa.Column('thumbnail_key', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('course_type', sa.String(length=10), server_default='free', nullable=False))
    op.add_column('courses', sa.Column('price_naira', sa.Integer(), server_default='0', nullable=False))
    op.add_column('courses', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    op.create_index(op.f('ix_courses_creator_user_id'), 'courses', ['creator_user_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'users', ['creator_user_id'], ['id'])
    op.add_column('users', sa.Column('is_creator', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_creator')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_creator_user_id'), table_name='courses')
    op.drop_column('courses', 'status')
    op.drop_column('courses', 'price_naira')
    op.drop_column('courses', 'course_type')
    op.drop_column('courses', 'thumbnail_key')
    op.drop_column('courses', 'requirements')
    op.drop_column('courses', 'target_audience')
    op.drop_column('courses', 'outcomes')
    op.drop_column('courses', 'category')
    op.drop_column('courses', 'creator_user_id')
    op.drop_index(op.f('ix_creator_profiles_user_id'), table_name='creator_profiles')
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
